# Generated by Django 6.0.5 on 2026-05-29 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('payload', models.JSONField(default=dict)),
                ('job_type', models.CharField(max_length=256)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal')], default='NORMAL', max_length=16)),
                ('state', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('QUEUED', 'Queued'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('CANCELLED', 'Cancelled'), ('CHECKPOINTED', 'Checkpointed'), ('PREEMPTED', 'Preempted'), ('DEAD_LETTER', 'Dead Letter')], db_index=True, default='SUBMITTED', max_length=16)),
                ('attempt', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('timeout_seconds', models.IntegerField(default=3600)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='SchedulerLeader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('holder_id', models.CharField(max_length=64)),
                ('acquired_at', models.DateTimeField()),
                ('renewed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'scheduler_leader',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('max_concurrent_jobs', models.IntegerField(default=10)),
                ('max_workers', models.IntegerField(default=5)),
                ('priority_boost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=256)),
                ('pid', models.IntegerField()),
                ('tenant_inflight_job_count_map', models.JSONField(default=dict)),
                ('max_inflight_jobs', models.IntegerField(default=4)),
                ('inflight_job_count', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('ONLINE', 'Online'), ('DRAINING', 'Draining'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=16)),
                ('last_heartbeat', models.DateTimeField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='DeadLetterJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_error', models.TextField(blank=True, null=True)),
                ('total_attempts', models.IntegerField()),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter', to='src.job')),
            ],
            options={
                'db_table': 'dead_letter_jobs',
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField()),
                ('storage_path', models.TextField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='src.job')),
            ],
            options={
                'db_table': 'checkpoints',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, null=True)),
                ('attempt', models.IntegerField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='src.job')),
            ],
            options={
                'db_table': 'job_events',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='src.tenant'),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, db_column='assigned_worker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='src.worker'),
        ),
    ]
