"""
Django settings for endure project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env_file = BASE_DIR / ".env"
if env_file.exists():
    env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-nc*a9m9v$9hi)k!mb_)(%pmz05h$#jp+qwg^+-d!md$o)997an"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "src",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "endure.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "endure.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("ENDURE_DATABASE_NAME"),
        "USER": env.str("ENDURE_DATABASE_USER"),
        "PASSWORD": env.str("ENDURE_DATABASE_PASSWORD"),
        "HOST": env.str("ENDURE_DATABASE_HOST"),
        "PORT": env.str("ENDURE_DATABASE_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# ---------------------------------------------------------------------------
# Custom
# ---------------------------------------------------------------------------

API_HOST = env.str("ENDURE_API_HOST", default="0.0.0.0")
API_PORT = env.int("ENDURE_API_PORT", default=8000)

SCHEDULER_LOOP_INTERVAL = env.float("ENDURE_SCHEDULER_LOOP_INTERVAL", default=1.0)
LEADER_HEARTBEAT_INTERVAL = env.float("ENDURE_LEADER_HEARTBEAT_INTERVAL", default=5.0)
LEADER_LOCK_TTL = env.float("ENDURE_LEADER_LOCK_TTL", default=15.0)

WORKER_MAX_INFLIGHT_JOBS = env.int("ENDURE_WORKER_MAX_INFLIGHT_JOBS", default=4)
WORKER_HEARTBEAT_INTERVAL = env.float("ENDURE_WORKER_HEARTBEAT_INTERVAL", default=5.0)
WORKER_HEARTBEAT_TIMEOUT = env.float("ENDURE_WORKER_HEARTBEAT_TIMEOUT", default=30.0)

DEFAULT_JOB_TIMEOUT = env.int("ENDURE_DEFAULT_JOB_TIMEOUT", default=3600)
DEFAULT_MAX_RETRIES = env.int("ENDURE_DEFAULT_MAX_RETRIES", default=3)
RETRY_BASE_DELAY = env.float("ENDURE_RETRY_BASE_DELAY", default=5.0)
RETRY_MAX_DELAY = env.float("ENDURE_RETRY_MAX_DELAY", default=300.0)

CHECKPOINT_DIR = env.str("ENDURE_CHECKPOINT_DIR", default="/tmp/endure-checkpoints")

USE_PROCESS_ISOLATION = env.bool("ENDURE_USE_PROCESS_ISOLATION", default=False)

SCHEDULER_INSTANCE_ID = env.str("ENDURE_SCHEDULER_INSTANCE_ID", default="")

REDIS_URL = env.str("ENDURE_REDIS_URL", default="redis://localhost:6379/0")

REPORT_OUTPUT_DIR = env.str("ENDURE_REPORT_OUTPUT_DIR", default="/tmp/endure-reports")
