# Generated by Django 6.0.5 on 2026-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_job_run_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepoutput',
            name='error',
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('QUEUED', 'Queued'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('CANCELLED', 'Cancelled'), ('DEAD_LETTER', 'Dead Letter')], db_index=True, default='SUBMITTED', max_length=16),
        ),
        migrations.AlterField(
            model_name='worker',
            name='state',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together={('job', 'sequence_number')},
        ),
    ]
