# Generated by Django 6.0.5 on 2026-06-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_stepoutput_stage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepoutput',
            options={'ordering': ['stage_name', 'step_id']},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='inflight_job_count',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='tenant_inflight_job_count_map',
        ),
    ]
